### PR TITLE
Temporary fix for Header.

### PR DESCRIPTION
**Pull request by phaazon**
Fix for `Header` and `Maybe` in the generated code.

See https://github.com/haskell-servant/servant/pull/843 for further details.

> The `stack.yaml` file was altered so that I can successfully have it compiled with the latest servant and servant-foreign.

### CODE REVIEW

**Comment by phaazon** [comment]
Any news on that pals? :)

**Comment by phaazon** [comment]
Sure, I didn’t see those. I’ll fix them. Maybe @alp might know when it’ll get released?

**Comment by alpmestan** [comment]
Oh we can definitely merge several outstanding PRs and ship a new release reasonably soon (upcoming weeks -- can't make it more precise, I've been a bit busy with another servant related thing that we might "ship" too at the same time).

**Comment by alpmestan** [comment]
I just merged the servant PR though.

**Comment by phaazon** [comment]
That should be okay now!

**Comment by phaazon** [comment]
Friendly ping.

**Comment by phaazon** [comment]
(I’ll also change that `stack.yaml` thing, since we might be able to use a nightly with the correct servant version now).

**Comment by phaazon** [comment]
It works with a proper `stack.yaml`. What should I do to clean it up completely, and have a new version of `servant-elm` released?

**Comment by phaazon** [comment]
Peeps? :)

**Comment by mattjbray** [comment]
Hi! Sorry for the long silence. I've just seen that Servant 0.13 has added `Required` and `Optional` modifiers for both `Header` and `QueryParam`, so I've updated this PR to support that. Thanks!

**Comment by phaazon** [comment]
Awesome, thanks!

**Pull request merged**
